spring.datasource.url=jdbc:postgresql://dpg-d7d50vkvikkc73du076g-a/tp_spring_db
spring.datasource.username=tp_spring_db_user
spring.datasource.password=kUdagSqD28SfJw5C5qIPC3fI53jiLEl9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=10000
